const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const d={ref:'Bava Metzia 21b',settings:{},failures:[],wordCounts:{gemara:300,inner:400,tosafot:200},unplacedCounts:{gemara:0,inner:0,tosafot:0}};
const context={window:{},diagnostics:d,approvalFailures:()=>context.diagnostics.failures};vm.createContext(context);
vm.runInContext(fs.readFileSync('agent-builder/agent-brain.js','utf8'),context);
const source=fs.readFileSync('agent-builder/app.js','utf8');
vm.runInContext(source.slice(source.indexOf('function teacherCommandStream'),source.indexOf('function sendAdjustment')),context);
const brain=context.window.VilnaAgentBrain;
const review=(note,targetRegion='whole-page')=>brain.review({diagnostics:context.diagnostics,feedback:{note,targetRegion}},context.localAgentReview);
assert.equal(review('The gutter needs to surround the gemara on all sides').changes.enforceGemaraGutterBox,true);
assert.equal(review('Keep only four opening commentary lines').changes.openingLines,4);
assert.equal(review('The last 4 lines of tosfos are seperate from the rest').changes.enforceStreamContinuity,true);
assert.equal(review('Remove gemorah dashes','tosafos').changes.stripGemaraDashes,true,'Explicitly named stream wins over stale dropdown');
assert.equal(review('Gemara should have 54 lines').changes.targetLineCounts.gemara,54);
assert.equal(review('Make the Gemara 51 lines total').changes.targetLineCounts.gemara,51);
assert.equal(review('From Gemara line 45 onward widen into the Rashi region').changes.expansionLine,45);
assert.equal(review('From Gemara line 45 onward widen into the Rashi region').changes.expansionIntoStream,'inner');
assert.equal(review('From Gemara line 45 onward widen into Rashi','tosafos').changes.expansionStream,'gemara');
const anchor=review('Gemara line 2 starts with "אמר רב" and ends with "תיקו"');
assert.equal(anchor.changes.lineAnchors[0].line,2);
assert.equal(anchor.changes.lineAnchors[0].startText,'אמר רב');
const combined=review('Keep only four opening commentary lines; surround the Gemara with a gutter on all sides; remove Gemara dashes');
assert.equal(combined.changes.openingLines,4);assert.equal(combined.changes.enforceGemaraGutterBox,true);assert.equal(combined.changes.stripGemaraDashes,true);
const conjunction=review('Gemara should have 54 lines and remove Gemara dashes');
assert.equal(conjunction.changes.targetLineCounts.gemara,54);assert.equal(conjunction.changes.stripGemaraDashes,true);
assert.equal(review('Alighn Gemorah line 45 to the right').changes.gemaraAlignmentLine,45);
assert.equal(review('Tosafos should have 70 lines; Rashi should have 80 lines').changes.targetLineCounts.inner,80);
assert.equal(review('Widen the Gemara').unresolved.length,1,'Missing line boundary stays explicit');
assert(!Object.keys(review('Change something mysterious').changes).length);
context.diagnostics={...d,failures:['tosafot rendered text is clipped'],unplacedCounts:{gemara:0,inner:0,tosafot:20}};
assert.equal(review('').changes.pageHeight,1078);
assert.equal(brain.diagnose({...d,failures:['opening commentary continuity']}).changes.openingLines,4);
assert(!Object.keys(brain.diagnose({...d,failures:['source load: unavailable']}).changes).length);
assert(!Object.keys(brain.diagnose(d).changes).length);
assert.equal(brain.worse([1,0,0],[0,1,5]),true);
assert.equal(brain.worse([0,0,1],[0,0,4]),false);
// Exercise repair state transitions: improvement, worsening/rollback, retry limit, explicit undo.
let sent=[];const nodes={};
const repairContext={diagnostics:structuredClone(d),pendingAdjustment:null,lastAdjustment:null,structuredClone,Set,JSON,VilnaAgentBrain:brain,frame:{contentWindow:{postMessage(data){sent.push(data)}}},location:{origin:'https://test'},$:id=>nodes[id]||(nodes[id]={}),renderDiagnostics(){},message(){}};
vm.createContext(repairContext);vm.runInContext(source.slice(source.indexOf('function sendAdjustment'),source.indexOf('$("applyAgent").addEventListener')),repairContext);
repairContext.sendAdjustment({openingLines:4});repairContext.finishAdjustment({...d,failures:['new failure']});assert.equal(sent.at(-1).type,'vilna-agent-replace-settings');assert.equal(repairContext.pendingAdjustment.restoring,true);
repairContext.finishAdjustment(d);assert.equal(repairContext.pendingAdjustment,null);
repairContext.diagnostics={...d,failures:['text overflow'],textOverflow:true,settings:{pageHeight:1030}};
repairContext.sendAdjustment({pageHeight:1078},{repair:true});
for(const height of [1078,1126,1174])repairContext.finishAdjustment({...repairContext.diagnostics,settings:{pageHeight:height}});
assert.equal(repairContext.pendingAdjustment,null);assert.equal(sent.filter(x=>x.type==='vilna-agent-adjust').length,4,'Initial manual adjustment plus three repair attempts');
repairContext.diagnostics=structuredClone(d);repairContext.sendAdjustment({pageHeight:900},{replace:true,userRestore:true});repairContext.finishAdjustment({...d,failures:['earlier failure']});assert.equal(repairContext.pendingAdjustment,null,'Explicit undo is honored');
repairContext.diagnostics=structuredClone(d);repairContext.sendAdjustment({},{replace:true,userRestore:true});assert(repairContext.pendingAdjustment,'Undo can restore an empty original settings object');repairContext.finishAdjustment(d);
console.log('PASS: natural correction examples, stale dropdown, combined operations, evidence gaps, measured repairs, rollback, three-attempt bound, and undo.');

// Run the actual gutter check body: it must read the page gutter locally.
const engine=fs.readFileSync('draft-engine/app.js','utf8');
const gutterStart=engine.indexOf('if(state.agentSettings.enforceGemaraGutterBox){');
const gutterEnd=engine.indexOf('return[...new Set(failures)]',gutterStart);
let top=25,bottom=25;const gutterContext={state:{agentSettings:{enforceGemaraGutterBox:true}},failures:[],streamRegions:()=>[{edge:'top'},{edge:'bottom'}],$:()=>({edge:'page'}),getComputedStyle:el=>el.edge==='page'?{getPropertyValue:()=>25}:{paddingTop:top,paddingBottom:bottom},parseFloat};
vm.createContext(gutterContext);vm.runInContext(engine.slice(gutterStart,gutterEnd),gutterContext);assert.equal(gutterContext.failures.length,0);
bottom=0;vm.runInContext(engine.slice(gutterStart,gutterEnd),gutterContext);assert.equal(gutterContext.failures[0],'Gemara top/bottom gutter');
assert(engine.includes('postAgentDiagnostics([`adjustment failed: ${error.message}`])'));
console.log('PASS: gutter validator runtime scope and missing-bottom-wall rejection.');
